[NEW] introduce permission system into apps-engine
RocketChat/Rocket.Chat.Apps-engine pull request #346
Opened 2020-11-12 14:30 UTC by lolimay

# What? :boat:

This PR tries to introduce Permission System into the apps-engine.

It still a Proof Of Concept (PoC) at the moment (a.k.a in a very early stage), so it might be changed a lot as our discussion continues.

# Why? :thinking:

# Links :earth_americas:

https://app.clickup.com/t/98bbwn

# PS :eyes:

2020-12-16 23:35 UTC, d-gubert requested changes

2020-12-17 12:57 UTC, lolimay commented on src/definition/permission/IPermissionCheckers.ts
> +export interface IPermissionCheckers {
ah, makes sense. Thanks for the note!

2020-12-21 17:19 UTC, thassiov commented on src/definition/permissions/IPermission.ts
> +    requierd?: boolean;
typo here ;)

2020-12-21 22:13 UTC, thassiov commented on src/server/AppManager.ts
> +        const { enable, marketplaceInfo, permissionsGranted } = installationParameters;
`enable` now does not have the default value `true`, making newly added apps to be disabled after installation. I'm changing this :grin:

2020-12-22 18:18 UTC, thassiov commented
LGTM so far

2021-01-22 20:47 UTC, d-gubert approved these changes

2021-01-22 20:49 UTC, merged