[FEAT]: Add `skipImmediate` property to the IRecurringSchedule interface
RocketChat/Rocket.Chat.Apps-engine pull request #403
Opened 2021-04-12 13:40 UTC by thassiov

# What? :boat:

Adds a property lets the developer decide whether they want the first iteration of a recurring task to be executed immediately instead of waiting for the defined interval to complete

# Why? :thinking:

# Links :earth_americas:

# PS :eyes:

2021-04-12 17:39 UTC, lolimay approved these changes

2021-04-13 14:21 UTC, d-gubert requested changes

2021-04-13 14:21 UTC, d-gubert commented on src/definition/scheduler/IRecurringSchedule.ts
> +     * Whether to let the first iteration to execute as soon as the task is registered
Bit of rewording, wdyt?

```suggestion
     * Whether the recurring job should start immediately or wait for the interval
```

2021-04-14 22:21 UTC, d-gubert approved these changes

2021-04-14 22:22 UTC, merged