[CHORE] Remove codecov config
RocketChat/Rocket.Chat.Apps-engine pull request #418
Opened 2021-05-19 13:41 UTC by thassiov

# What? :boat:

Remove codecov config

# Why? :thinking:

# Links :earth_americas:

# PS :eyes:

2021-05-19 13:43 UTC, lolimay approved these changes

2021-05-19 13:53 UTC, thassiov commented
@lolimay I'm going to dismiss your review as I didn't put the PR as a draft by mistake :grimacing: but I'll ask again for a review later. Thank you!

2021-05-26 21:07 UTC, d-gubert requested changes

2021-05-26 21:07 UTC, d-gubert commented on .circleci/config.yml
> -
Can we just comment it out instead? Will be easier to reintroduce this step when we're ready 😬

2021-05-26 21:51 UTC, d-gubert commented on .circleci/config.yml
> -
Nah, forget it

2021-05-26 21:51 UTC, d-gubert approved these changes

2021-06-01 12:51 UTC, merged