[FEAT] Open uikit contextual bar
RocketChat/Rocket.Chat.Apps-engine pull request #451
Opened 2021-11-03 12:50 UTC by thassiov

# What? :boat:

# Why? :thinking:

# Links :earth_americas:

# PS :eyes:

2021-11-11 13:09 UTC, d-gubert requested changes

2021-11-11 13:09 UTC, d-gubert commented on src/definition/uikit/UIKitInteractionPayloadFormatter.ts
> +        UIKitInteractionType.CONTEXTUAL_BAR_CLOSE].includes(context.type)) {
If we use a type guard function to validated `context.type`, Typescript will be able to tell the actual type of the property

2021-11-12 02:49 UTC, cuonghuunguyen commented
as we had a permission system with Apps Engine, should we allow apps to display Contextual Bar and  Modal without the initial interaction from users?
I am making an app for livechat agents to send transfer request to the other agents. Without modals I am having to use a very compilated custom script

2021-11-17 00:32 UTC, d-gubert commented
> as we had a permission system with Apps Engine, should we allow apps to display Contextual Bar and Modal without the initial interaction from users?

We were not considering making that change, as it is somewhat risky... as in, without this restriction, what will stop apps from spamming modals to users? 🤔

2021-11-17 20:18 UTC, graywolf336 commented
> We were not considering making that change, as it is somewhat risky... as in, without this restriction, what will stop apps from spamming modals to users? 🤔
The developers themselves and the marketplace publisher review team. What's to stop an app from spamming messages to users? If we use this same logic in other areas then we willcontinuouslyy hinder apps and what they can do. In my opinion

2021-11-29 00:23 UTC, d-gubert commented
> The developers themselves and the marketplace publisher review team.

Having to check for this kind of "bad" behavior in the review process is not scalable.

We've decided to follow this practice as it is something Slack also does, and it looked very reasonable. But we can discuss about this again, of course.


> What's to stop an app from spamming messages to users?

This argument could go the other way as well. Like, shouldn't we implement some kind of "rate limiter" to say the least so apps would not abuse this power? Might fall in the same discussion mentioned above 🤷

2021-11-29 15:52 UTC, graywolf336 commented
In all honesty, I think us erroring on the "safe side" is curtailing creativity more than it's preventing people from spamming. Just my two cents :)

2021-11-30 03:56 UTC, cuonghuunguyen commented
Agree with @graywolf336, we can't prevent all the cases of spamming. But imagine, if we're more open to the Apps Engine, we can bring thousands ideas into life 😄

2021-12-20 19:49 UTC, d-gubert approved these changes

2021-12-20 19:49 UTC, merged