[NEW] Add new events after user has been created, updated and deleted
RocketChat/Rocket.Chat.Apps-engine pull request #499
Opened 2022-04-12 15:20 UTC by tapiarafael

# What? :boat:
Add definition and listeners for new events `IPostUserCreated`, `IPostUserUpdated` and `IPostUserDeleted`

# Why? :thinking:

# Links :earth_americas:
[Task](https://app.clickup.com/t/22wqd4p)

# PS :eyes:

2022-04-12 15:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=499) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=499) before we can accept your contribution.<br/><hr/>**Rafael Tapia** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Apps-engine?pullRequest=499) it.</sub>

2022-04-14 12:25 UTC, d-gubert requested changes

2022-04-14 12:25 UTC, d-gubert commented on src/server/managers/AppListenerManager.ts
> +        const context = Object.freeze(data);
`Object.freeze` performs a shallow freeze only, in these cases it's better to use `Utilities.deepFreeze` to ensure inner objects are also frozen

2022-04-14 12:25 UTC, d-gubert commented on src/definition/users/IUserContext.ts
> +}
It would be good to add some comments here explaining app devs what is the purpose of the interface and the properties

2022-04-14 12:25 UTC, d-gubert commented on src/definition/users/IUserUpdateContex.ts
> +}
It would be good to add some comments here explaining app devs what is the purpose of the interface and the properties

2022-04-28 14:27 UTC, thassiov approved these changes
LGTM

2022-05-02 22:00 UTC, d-gubert approved these changes

2022-05-02 22:00 UTC, merged