[New] Support for x-www-form-urlencoded Body Params in OAuth2 calls
RocketChat/Rocket.Chat.Apps-engine pull request #554
Opened 2022-11-12 13:40 UTC by mustafahasankhan

# What? :boat:

- Added support for OAuth2 Clients that require parameters in Body as x-www-form-urlencoded Content-Type.
- Backwards compatible, does not affect client that don't require parameters in Body.

# Why? :thinking:

We need this in using Microsoft Graph API and other OAuth2 Clients.

# Links :earth_americas:

# PS :eyes:

2022-11-12 13:40 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=554) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=554) before we can accept your contribution.<br/><hr/>**mustafahasankhan** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Apps-engine?pullRequest=554) it.</sub>

2022-11-16 16:21 UTC, AllanPazRibeiro requested changes

2022-11-16 16:21 UTC, AllanPazRibeiro commented on src/server/oauth2/OAuth2Client.ts
> +                            Authorization successful.<br>\
I will ask you to let this message as it was previously

2022-11-16 17:26 UTC, AllanPazRibeiro submitted a review, later dismissed

2022-11-16 17:36 UTC, thassiov submitted a review, later dismissed

2022-11-16 18:01 UTC, AllanPazRibeiro approved these changes

2022-11-16 18:02 UTC, mustafahasankhan commented
Leaving this comment for the CLA-assistant so that it refreshes the CLA check for this PR.

2022-11-16 21:10 UTC, d-gubert commented
I'll merge this. The CLA is complaining about the two first commits that haven't been made with the correct configuration, and fixing that would be a hassle, so we'll just ignore it in this case

2022-11-16 21:11 UTC, merged