[NEW] Introduce new bridge to provide moderation related features 0.1
RocketChat/Rocket.Chat.Apps-engine pull request #593
Opened 2023-03-07 07:21 UTC by Dnouv

# What? :boat:

- Added x (where x="the bridge for reporting a message")
- Updated `AppsPermissions.ts`

# Why? :thinking:

For the Moderation project, I have on the TODO an Auto-reporter app, which will require this `reportMessage` function in core available to access from the App.

# Links :earth_americas:

Coming soon...

# PS :eyes:
Thank you!

2023-03-07 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Apps-engine?pullRequest=593) it.</sub>

2023-03-07 07:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=593) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/RocketChat/Rocket.Chat.Apps-engine?pullRequest=593) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/RocketChat/Rocket.Chat.Apps-engine?pullRequest=593) it.</sub>

2023-04-12 14:09 UTC, tapiarafael requested changes

2023-04-12 14:09 UTC, tapiarafael commented on src/server/bridges/ModerationBridge.ts
> +    // private hasReadPermission(appId: string): boolean {
Forgot to remove

2023-04-12 18:23 UTC, Dnouv commented on src/definition/accessors/IModerationModify.ts
> +     * Provides a way for Apps to report a message.
Thank you! Yes, indeed, my bad, I missed it, but now it is resolved.

2023-04-13 14:00 UTC, tapiarafael commented
Everything looks good to me. We just need to merge the RC PR first to avoid breaking apps.engine.
https://github.com/RocketChat/Rocket.Chat/pull/28518

2023-04-14 22:19 UTC, d-gubert approved these changes

2023-04-14 22:20 UTC, merged